# SPDX-FileCopyrightText: 2025 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Build Latest Image
on:
  schedule:
    - cron: 35 * * * *
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  nextcloud:
    name: Get Version Information
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
      major_tag: ${{ steps.image_tags.outputs.major_tag }}
      minor_tag: ${{ steps.image_tags.outputs.minor_tag }}
      patch_tag: ${{ steps.image_tags.outputs.patch_tag }}
    steps:
      - name: Get Latest Nextcloud Version
        id: version
        uses: joepitt91/action-version-from-dockerhub@v1
        with:
          dockerhub_username: ${{ secrets.DOCKER_USER }}
          dockerhub_token: ${{ secrets.DOCKER_PASSWORD }}
          repository: nextcloud

      - name: Get Current Digest for Identified Version
        id: digest
        uses: joepitt91/action-digest-from-dockerhub-image@v1
        with:
          dockerhub_username: ${{ secrets.DOCKER_USER }}
          dockerhub_token: ${{ secrets.DOCKER_PASSWORD }}
          repository: nextcloud
          tag: ${{ steps.version.outputs.tag }}

      - name: Convert Version to Tags
        id: image_tags
        uses: joepitt91/action-version-to-tags@v1
        with:
          version: ${{ steps.version.outputs.version }}

  build:
    name: Build Image
    if: needs.nextcloud.outputs.digest != vars.BASE_IMAGE || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
      - nextcloud
    steps:
      - name: Image Information
        run: echo "Building image of Nextcloud ${{ needs.nextcloud.outputs.version }} from image with digest ${{ needs.nextcloud.outputs.digest }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXTCLOUD_VERSION=${{ needs.nextcloud.outputs.tag }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/nextcloud:latest
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.major_tag }}
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.minor_tag }}
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.patch_tag }}

  save_versions:
    name: Save Versions
    needs: 
      - build
      - nextcloud
    runs-on: ubuntu-latest
    steps:
      - name: Update BASE_IMAGE
        uses: mmoyaferrer/set-github-variable@v9.9.5
        with:
          name: BASE_IMAGE
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          value: ${{ needs.nextcloud.outputs.digest }}