# SPDX-FileCopyrightText: 2025 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Build Specific Version Image
on:
  schedule:
    - cron: 35 * * * *
  workflow_dispatch:
    inputs:
      version:
        description: The version to build, e.g. 31.0.5
        required: true
        type: string
      tag_level:
        default: patch
        description: The highest level of tagging to apply.
        options:
          - major
          - minor
          - patch
        required: false
        type: choice
permissions:
  contents: read
  packages: write
jobs:
  nextcloud:
    name: Get Version Information
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
      major_tag: ${{ steps.image_tags.outputs.major_tag }}
      minor_tag: ${{ steps.image_tags.outputs.minor_tag }}
      patch_tag: ${{ steps.image_tags.outputs.patch_tag }}
    steps:
      - name: Get Current Digest for Specified Version
        id: digest
        uses: joepitt91/action-digest-from-dockerhub-image@v1
        with:
          dockerhub_username: ${{ secrets.DOCKER_USER }}
          dockerhub_token: ${{ secrets.DOCKER_PASSWORD }}
          repository: nextcloud
          tag: ${{ inputs.version }}

      - name: Convert Version to Tags
        id: image_tags
        uses: joepitt91/action-version-to-tags@v1
        with:
          version: ${{ inputs.version }}

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs:
      - nextcloud
    steps:
      - name: Image Information
        run: echo "Building image of Nextcloud ${{ inputs.version }} from image with digest ${{ needs.nextcloud.outputs.digest }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image (major)
        if: inputs.tag_level == 'major'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXTCLOUD_VERSION=${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.major_tag }}
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.minor_tag }}
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.patch_tag }}

      - name: Build and Push Image (minor)
        if: inputs.tag_level == 'minor'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXTCLOUD_VERSION=${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.minor_tag }}
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.patch_tag }}

      - name: Build and Push Image (patch)
        if: inputs.tag_level == 'patch'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            NEXTCLOUD_VERSION=${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/nextcloud:${{ needs.nextcloud.outputs.patch_tag }}