# SPDX-FileCopyrightText: 2025 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Build Latest Images
on:
  schedule:
    - cron: 35 * * * *
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  versions:
    name: Version Information
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.build_needed.outputs.needed }}
      base_image: ${{ steps.base_image.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        env:
          PIP_ROOT_USER_ACTION: ignore
        run: |
          python3 -m pip install -q --upgrade pip
          pip install -q -r version_checker/requirements.txt

      - id: base_image
        name: Get Base Image Digest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPOSITORY: library/nextcloud
          DOCKER_TAG: 'latest'
          DOCKER_USER: ${{ secrets.DOCKER_USER }}  
        run: |
          cd version_checker/
          python3 docker_image.py >>$GITHUB_OUTPUT

      - id: build_needed
        name: Check if a New Build is Required
        run: |
          if [ "${{ steps.base_image.outputs.digest }}" == "${{ vars.BASE_IMAGE }}"  ]; then
            echo "needed=no" >>$GITHUB_OUTPUT
          else
            echo "needed=yes" >>$GITHUB_OUTPUT
          fi

  build:
    name: Build Images
    if: needs.versions.outputs.build == 'yes' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs:
      - versions
    steps:
      - name: Image Information
        run: echo "Building image of Nextcloud from nextcloud:latest with digest ${{ needs.versions.outputs.base_image }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/nextcloud:latest
            ghcr.io/joepitt91/nextcloud:run_${{ github.run_number }}

  save_versions:
    name: Save Versions
    needs: 
      - build
      - versions
    runs-on: ubuntu-latest
    steps:
      - name: Update BASE_IMAGE
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: BASE_IMAGE
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          value: ${{ needs.versions.outputs.base_image }}
